$(function(){
	addFooter();
})

function addFooter(){
	var sb='   <div class="footer"> ';
	sb+='    <div class="footer_con"> ';
	sb+='     <div class="footer_dl"> ';
	sb+='      <dl> ';
	sb+='       <dt>';
	sb+='        关于';
	sb+='       </dt> ';
	sb+='       <dd>';
	sb+='        <a href="about.html">关于我们</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="service.html">服务项目</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="contact.html">联系我们</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="/contact/pay.html">付款方式</a>';
	sb+='       </dd> ';
	sb+='      </dl> ';
	sb+='      <dl> ';
	sb+='       <dt>';
	sb+='        经典案例';
	sb+='       </dt> ';
	sb+='       <dd>';
	sb+='        <a href="/cases/list-3-1.html">企业网站</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="/cases/list-8-1.html">旅游网站</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="/cases/list-9-1.html">购物商城</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="/cases/list-10-1.html">外贸网站</a>';
	sb+='       </dd> ';
	sb+='      </dl> ';
	sb+='      <dl> ';
	sb+='       <dt>';
	sb+='        服务范围';
	sb+='       </dt> ';
	sb+='       <dd>';
	sb+='        <a href="service.html">空间域名</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="service.html">网站策划</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="service.html">网站建设</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <a href="service.html">手机网站</a>';
	sb+='       </dd> ';
	sb+='      </dl> ';
	sb+='      <dl class="footer_dl2" style="width:340px;"> ';
	sb+='       <dt>';
	sb+='        联系我们';
	sb+='       </dt> ';
//	sb+='       <dd>';
//	sb+='        <img src="images/xinlang.png" alt="网络官方微博" />';
//	sb+='        <a href="http://weibo.com/szfangwei" rel="noFollow" target="_blank">官方微博: http://weibo.com/</a>';
//	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <img src="images/mail.png" alt="网站建设咨询邮箱" />';
	sb+='        <a href="mailto:houzhanwu365@126.com / houzhanwu365@163.com">咨询邮箱：houzhanwu365@126.com</a>';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <img src="images/tel.png" alt="网站建设咨询电话" />咨询热线：18713417921 / 17610306792';
	sb+='       </dd> ';
	sb+='       <dd>';
	sb+='        <img src="images/weixin.png" alt="网站建设" />微信：houzhanwu666666 / houzhanwu_test';
	sb+='       </dd> ';
	sb+='      </dl> ';
	sb+='       <dl class="footer_dl3"> ';
	sb+='        <dt>';
	sb+='         给我们留言';
	sb+='        </dt> ';
	sb+='        <dd> ';
	sb+='         <input id="name" class="input" type="text" placeholder="称呼（必填）" /> ';
	sb+='        </dd> ';
	sb+='        <dd> ';
	sb+='         <input id="tel" class="input" type="text" placeholder="电话（必填）"  /> ';
	sb+='        </dd> ';
	sb+='        <dd> ';
	sb+='         <textarea id="content" cols="" rows=""></textarea> ';
	sb+='        </dd> ';
	sb+='        <dd>';
	sb+='         <input type="image" id="submit" alt="提交留言" onclick="send()" src="images/submit_button.png" />';
	sb+='        </dd> ';
	sb+='       </dl> ';
	sb+='      <div class="clear"></div> ';
	sb+='     </div> ';
	sb+='     <div class="link">';
	sb+='      友情链接： ';
	sb+='      <a href="http://www.mountor.cn" target="_blank">网站设计</a>';
	sb+='      <a href="http://www.580jz.net/" target="_blank">商城网站建设</a>';
	sb+='      <a href="http://www.km-jz.cn" target="_blank">昆明网站建设</a>';
	sb+='      <a href="http://www.99seo.cn" target="_blank">合肥网站建设</a>';
	sb+='      <a href="http://www.ynhl.net" target="_blank">北京网站建设</a>';
	sb+='      <a href="http://www.zwzsh.net" target="_blank">上海网站建设</a>';
	sb+='      <a href="http://www.zhubajie.com/wzkf/" target="_blank">网站建设</a>';
	sb+='      <a href="http://www.zhuyun.cn" target="_blank">网店系统</a>';
	sb+='      <a href="http://www.wanhu.cn/" target="_blank">企业网站建设</a>';
	sb+='      <a href="http://www.yuanxp.com" target="_blank">都江堰网络公司</a>';
	sb+='      <a href="http://www.parabnet.com" target="_blank">南京网站建设</a>';
	sb+='      <a href="http://www.xw0371.com" target="_blank">郑州网站建设</a>';
	sb+='      <a href="http://www.thyoo.com" target="_blank">康辉国旅</a>';
	sb+='      <a href="http://www.shenzhenshiye.com" target="_blank">深圳包装设计公司</a>';
	sb+='      <a href="http://www.sino-web.net" target="_blank">网站建设公司</a>';
	sb+='      <a href="http://www.jxbh.cn" target="_blank">南昌网站建设</a>';
	sb+='      <a href="http://www.zysj360.com" target="_blank">北京网页设计</a>';
	sb+='      <a href="http://www.billionseo.com/" target="_blank">大连网站制作公司</a>';
	sb+='      <a href="http://www.weibug.com/" target="_blank">西部数码代理</a>';
	sb+='      <a href="http://www.gggooo.com/" target="_blank">网站托管</a>';
	sb+='      <a href="http://www.bluehost.com.cn/" target="_blank">bluehost</a>';
	sb+='      <a href="http://www.72en.net/" target="_blank">全国网站建设</a>';
	sb+='      <a href="http://www.99seo.cn/" target="_blank">合肥网站建设</a>';
	sb+='      <a href="http://www.ft0451.cn/" target="_blank">哈尔滨网站建设</a>';
	sb+='      <a href="http://www.zzhpkj.com/" target="_blank">郑州网站建设公司</a>';
	sb+='      <a href="http://www.usa-idc.com/" target="_blank">香港服务器租用</a>';
	sb+='      <a href="http://www.csweimin.cn" target="_blank">长沙网站制作</a>';
	sb+='      <a href="http://www.2d2y.net/" target="_blank">全国网站建设</a>';
	sb+='      <a href="http://www.nmgf.net" target="_blank">内蒙古网站建设</a>';
	sb+='      <a href="http://www.zjcoo.com" target="_blank">重庆网站建设</a>';
	sb+='      <a href="http://www.wangzhan360.com" target="_blank">北京制作网站</a>';
	sb+='      <a href="http://www.whsdgx.com" target="_blank">武汉网站建设</a>';
	sb+='      <a href="http://www.ihanshi.com" target="_blank">网站建设</a>';
	sb+='      <a href="http://host.zzidc.com" target="_blank">免费虚拟空间</a>';
	sb+='      <a href="http://www.tfxk.com " target="_blank">成都网站建设</a>';
	sb+='      <a href="http://www.hejun.com.cn" target="_blank">北京网站建设</a>';
	sb+='      <a href="http://www.wanyumi.com " target="_blank">域名注册</a>';
	sb+='      <a href="http://www.da-mai.com" target="_blank">网店托管</a>';
	sb+='      <a href="http://www.61916.com" target="_blank">全国网站建设</a>';
	sb+='      <a href="http://www.ymars.com" target="_blank">长沙网站建设</a>';
	sb+='      <a href="http://www.hefeiidc.cn" target="_blank">合肥网站建设</a> ';
	sb+='     </div> ';
	sb+='    </div> ';
	sb+='   </div> ';
	sb+='   <div class="bottom"> ';
	sb+='    <div class="bottom_con">';
	sb+='     @2013 版权所有 深圳网络科技有限公司 地址：深圳市罗湖区春风路桂都大厦';
	sb+='     <a href="http://www.miitbeian.gov.cn" rel="noFollow" style="color:#666;">粤ICP备16465465456号-2</a>';
	sb+='    </div> ';
	sb+='   </div> ';
	
	
	$("#footer").html(sb);
}